apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-navigation
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-navigation
  template:
    metadata:
      labels:
        app: site-navigation
    spec:
      containers:
      - name: site-navigation
        image: harbor.xxx.cn/devops/site_navigation:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
# service
apiVersion: v1
kind: Service
metadata:
  name: site-navigation
  namespace: devops
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: site-navigation
  type: NodePort

---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-navigation
  namespace: devops
spec:
  ingressClassName: nginx
  rules:
  - host: site.evescn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: site-navigation
            port:
              number: 80