# Generated by Django 3.2.5 on 2023-02-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env',
            name='name',
            field=models.CharField(max_length=32, verbose_name='环境名称'),
        ),
        migrations.AlterField(
            model_name='service',
            name='env_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.env', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=32, verbose_name='服务名称'),
        ),
        migrations.AlterField(
            model_name='service',
            name='password_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.password', verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(max_length=500, verbose_name='url地址'),
        ),
    ]
