# Generated by Django 3.2.5 on 2023-02-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230217_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='env',
            options={'verbose_name_plural': '环境表'},
        ),
        migrations.AlterModelOptions(
            name='password',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': '服务表'},
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=100, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='password',
            name='user',
            field=models.CharField(max_length=100, verbose_name='用户名'),
        ),
    ]
