# Generated by Django 3.2.5 on 2023-02-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230220_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='password_id',
        ),
        migrations.AddField(
            model_name='password',
            name='service_sid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.service', verbose_name='服务'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='env_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.env', verbose_name='环境'),
        ),
    ]
