# Generated by Django 3.2.5 on 2023-02-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_password_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户密码'),
        ),
    ]
